In [6]:
import pandas as pd

In [7]:
df=pd.read_csv(r"C:\Users\91904\Downloads\titanic\test2.csv")

In [8]:
print(df)

     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0      male  34.5      0      0              330911    7.8292   NaN        Q
1    female  47.0      1      0              363272    7.0000   NaN        S
2      male  62.0      0      0              240276    9.6875   NaN        Q
3      male  27.0      0      0              315154    8.6625   NaN        S
4    female  22.0      1      1             3101298   12.2875   NaN        S
..      ...   ...    ...    ...                 ...       ...   ...      ...
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S
414  female  39.0      0      0            PC 17758  108.9000  C105        C
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416    male   NaN      0      0              359309    8.0500   NaN        S
417    male   NaN      1      1                2668   22.3583   NaN        C

     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
413         0
414         1
415         0
416         1
417         1

[418 rows x 12 columns]

In [9]:
len(df[df["Survived"]==1])

163

In [10]:
len(df[df["Survived"]==0])

255

In [21]:
df[['Pclass','Survived']]

     Pclass  Survived
0         3         0
1         3         1
2         2         1
3         3         1
4         3         0
..      ...       ...
413       3         0
414       1         1
415       3         0
416       3         1
417       3         1

[418 rows x 2 columns]

In [30]:
len(df[df.Pclass==3])

218

In [24]:
# df['Pclass==1'] where df['Survived==1']

In [38]:
len(df[(df['Pclass']==1) & (df['Survived']==0)])

71

In [11]:
len(df[(df['Pclass']==3) & (df['Survived']==0)])

131

In [45]:
len(df[(df['Pclass']==1) & (df['Age']>18) & (df['Survived']==0)])

60

In [27]:
Data = [10,20,30]
datatable=pd.DataFrame(Data)
datatable

    0
0  10
1  20
2  30

In [33]:
Data = [[10,20,30],[10,20,30]]
datatable=pd.DataFrame(Data, columns=["Number","Age","phone"], index=["A","B"])
datatable

   Number  Age  phone
A      10   20     30
B      10   20     30

In [46]:
Above18=[[len(df[(df['Pclass']==1) & (df['Age']>18) & (df['Survived']==1)]),len(df[(df['Pclass']==2) & (df['Age']>18) & (df['Survived']==1)]),len(df[(df['Pclass']==3) & (df['Age']>18) & (df['Survived']==1)])],[len(df[(df['Pclass']==1) & (df['Age']>18) & (df['Survived']==0)]),len(df[(df['Pclass']==2) & (df['Age']>18) & (df['Survived']==0)]),len(df[(df['Pclass']==3) & (df['Age']>18) & (df['Survived']==0)])]]
c=pd.DataFrame(Above18, columns=["class1", "class2", "class3"], index=["survived","unsurvived"])
c.index.name="Above18"
print(c)

            class1  class2  class3
Above18
survived        33      34      43
unsurvived      60      41      67

In [ ]:
Below18=[[len(df[(df['Pclass']==1) & (df['Age']<18) & (df['Survived']==1)]),len(df[(df['Pclass']==2) & (df['Age']<18) & (df['Survived']==1)]),len(df[(df['Pclass']==3) & (df['Age']<18) & (df['Survived']==1)])],[len(df[(df['Pclass']==1) & (df['Age']<18) & (df['Survived']==0)]),len(df[(df['Pclass']==2) & (df['Age']<18) & (df['Survived']==0)]),len(df[(df['Pclass']==3) & (df['Age']<18) & (df['Survived']==0)])]]
c=pd.DataFrame(Below1818, columns=["class1", "class2", "class3"], index=["survived","unsurvived"])
c.index.name="Below18"
print(c)